[project]
name = 'climnode'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Community-Engagement]
path = 'contracts/Community-Engagement.clar'
clarity_version = 3
epoch = 3.0

[contracts.funding-allocation]
path = 'contracts/funding-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.governance-token]
path = 'contracts/governance-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact-tracking]
path = 'contracts/impact-tracking.clar'
clarity_version = 1
epoch = 2.05

[contracts.pool-funding]
path = 'contracts/pool-funding.clar'
clarity_version = 3
epoch = 3.0

[contracts.proposal-submission]
path = 'contracts/proposal-submission.clar'
clarity_version = 2
epoch = 2.5

[contracts.proposal-voting]
path = 'contracts/proposal-voting.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputaion-core]
path = 'contracts/reputaion-core.clar'
clarity_version = 3
epoch = 3.0

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.voting-mechanism]
path = 'contracts/voting-mechanism.clar'
clarity_version = 3
epoch = 3.0

[contracts.voting-token]
path = 'contracts/voting-token.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
