[project]
name = 'climnode'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Community-Engagement]
path = 'contracts/Community-Engagement.clar'
clarity_version = 3
epoch = 3.0

[contracts.proposal-submission]
path = 'contracts/proposal-submission.clar'
clarity_version = 2
epoch = 2.5

[contracts.proposal-voting]
path = 'contracts/proposal-voting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
